# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b94eabb6b3ba492651b94b3bf0ef6bcb09ce4c74befc811b68aa367da18526be6633d0c3fec77b09edf219b4ab9be0f8266042d2f6c087b823880551c1b55530

test:
  secret_key_base: ef12c90c90a84528ad4803d12e41775dcdf5a01cd22e44898919d5a77e886fd88be19cdf78b60cd67b907245d02a3d98ef9a24c2d991808ed5598fa74d7d266d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
