
## users 
User.create(firstname: "Karen", lastname: "Youssef", email: "kyoussef@qatar.cmu.edu", dietary_reqs: "None", password: "karen123", password_confirmation: "karen123", admin: 1)
User.create(firstname: "Manisha", lastname: "Dareddy", email: "mdaredd1@qatar.cmu.edu", dietary_reqs: "None", password: "manisha123", password_confirmation: "manisha123", admin: 0)
User.create(firstname: "Noor", lastname: "El-Sakka", email: "nelsakka@qatar.cmu.edu", dietary_reqs: "None", password: "noor123", password_confirmation: "noor123", admin: 0)
User.create(firstname: "Osama", lastname: "Ali", email: "oali@qatar.cmu.edu", dietary_reqs: "None", password: "osama123", password_confirmation: "osama123", admin: 0)
##-----------------------------------------------

## branches
Branch.create(name: "Carrefour Villagio", location: "Villagio", map: "")
##-----------------------------------------------

## products
Product.create(name: "Sweet Potato", category:"Vegetables", price: "12", brand: "US Veg") 
Product.create(name: "Chickpeas", category:"Vegetables", price: "12", brand: "US Veg") 
Product.create(name: "Garlic", category:"Vegetables", price: "12", brand: "US Veg") 
Product.create(name: "Parsley", category:"Vegetables", price: "12", brand: "US Veg") 
Product.create(name: "Tomato", category:"Vegetables", price: "12", brand: "US Veg") 
Product.create(name: "Fettucine", category:"Bakery", price: "12", brand: "Alali")
Product.create(name: "Almond Milk", category:"Dairy", price: "12", brand: "SoyFresh")
Product.create(name: "Soy Cream Cheese", category:"Dairy", price: "12", brand: "SoyFresh")
Product.create(name: "Almonds", category:"Snacks", price: "12", brand: "Alrifai")
Product.create(name: "Yeast", category:"Bakery", price: "12", brand: "Mr.Baker")
Product.create(name: "Salt", category:"Canned food", price: "12", brand: "Morton")
Product.create(name: "Lemon", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Extra Virgin Olive Oil", category:"Bakery", price: "12", brand: "Alali")
Product.create(name: "Soba Noodles", category:"Bakery", price: "12", brand: "Noodle Factory")
Product.create(name: "Edamame", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Sugar Snap Peas", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Carrots", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Cilantro", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Sesame seeds", category:"Vegetables", price: "12", brand: "Bisma")
Product.create(name: "Soy Sauce", category:"Canned food", price: "12", brand: "Thai Sauces")
Product.create(name: "Sesame Oil", category:"Canned food", price: "12", brand: "Oil Company")
Product.create(name: "Honey", category:"Snacks", price: "12", brand: "Shifaa")
Product.create(name: "Ginger", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Turkey", category:"Frozens", price: "12", brand: "Sadia")
Product.create(name: "Black Pepper", category:"Canned food", price: "12", brand: "Bisma")
Product.create(name: "Vegetable Oil", category:"Canned food", price: "12", brand: "Alali")
Product.create(name: "Onion", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Chicken Broth", category:"Chicken", price: "12", brand: "Maggi")
Product.create(name: "Dijon Mustard", category:"Canned food", price: "12", brand: "Knorr")
Product.create(name: "Thyme", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Flour", category:"Bakery", price: "12", brand: "Qatar Mill")
Product.create(name: "Squash", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Oregano", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Chilli Flakes", category:"Vegetables", price: "12", brand: "US Veg")
Product.create(name: "Ricotta", category:"Dairy", price: "12", brand: "Almarai")
Product.create(name: "Parmesan", category:"Dairy", price: "12", brand: "Almarai")
Product.create(name: "Eggs", category:"Eggs", price: "12", brand: "Qatari Eggs")
Product.create(name: "Pasta Sheets", category:"Bakery", price: "12", brand: "Alali")
Product.create(name: "Cerelac", category:"Baby food", price: "12", brand: "Nestle")
Product.create(name: "Breakfast Tea", category:"Tea/Coffee", price: "12", brand: "Lipton")
Product.create(name: "Nescafe", category:"Tea/Coffee", price: "12", brand: "Nescafe")
Product.create(name: "Dog food", category:"Pet food", price: "12", brand: "Pedigree")
Product.create(name: "Mango", category:"Fruits", price: "12", brand: "US Fruit")
Product.create(name: "Digestive", category:"Biscuits", price: "12", brand: "McVities")
Product.create(name: "Al Rayyan", category:"Newspaper", price: "12", brand: "Al Rayyan")
Product.create(name: "E!", category:"Magazines", price: "12", brand: "E!")
##-----------------------------------------------

## recipes
Recipe.create(name:"Mediterranean Baked Sweet Potatoes", dietaryreqs:"Vegan", serving:"2") 
Recipe.create(name:"Vegan Lemon Fettucine Alfredo", dietaryreqs:"Vegan", serving:"4") 
Recipe.create(name:"Sugar Snap Pea and Carrot Soba Noodles", dietaryreqs:"Vegan", serving:"2") 
Recipe.create(name:"Turkey with Dijon Gravy", dietaryreqs:"None", serving:"4") 
Recipe.create(name:"Roasted Winter Squash with Cilantro Chimichurri", dietaryreqs:"None", serving:"2") 
Recipe.create(name:"Four Cheese lasagna with Fresh Pasta", dietaryreqs:"None", serving:"4") 
##-----------------------------------------------

## product_recipes
ProductRecipe.create(product_id:"1", recipe_id:"1", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"2", recipe_id:"1", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"3", recipe_id:"1", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"4", recipe_id:"1", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"5", recipe_id:"1", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"6", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"7", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"8", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"9", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"10", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"11", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"12", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"13", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"3", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"4", recipe_id:"2", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"14", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"15", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"16", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"17", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"18", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"19", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"20", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"21", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"22", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"23", recipe_id:"3", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"24", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"11", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"25", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"26", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"27", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"3", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"28", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"29", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"30", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"31", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"4", recipe_id:"4", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"32", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"13", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"11", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"25", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"18", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"4", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"33", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"34", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"3", recipe_id:"5", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"35", recipe_id:"6", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"36", recipe_id:"6", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"37", recipe_id:"6", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"12", recipe_id:"6", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"4", recipe_id:"6", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"30", recipe_id:"6", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"38", recipe_id:"6", amount:"1", measurement: "unit")
ProductRecipe.create(product_id:"13", recipe_id:"6", amount:"1", measurement: "unit")
##-----------------------------------------------